name: Publish to PyPI

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [master, develop]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/') }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts from CI
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist/
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip-existing: true
        verbose: true
